version: '3.4'

services:
  redismessagequeue:
    image: ${DOCKER_REGISTRY-}redismessagequeue
    build:
      context: .
      dockerfile: RedisMessageQueue/Dockerfile

  redis-db:
    image: redis:latest
    ports:
        - "6379:6379"
    volumes:
        - ./redis:/redis

